### ISSUE TITLE
Time in rendered document only shows 1.1.1970

### ISSUE THREAD

**Issue by MandrakeRootes** [CutestNekoAqua/sbgg#2]
![image](https://github.com/user-attachments/assets/03b829a0-beea-4870-9ac2-4f79d4e85b01)

The time in the rendered document is 1.1.1970, probably because the time in the nix environment is set to 0

**Comment by aprilthepink** [comment]
oh no i didnt check for this. thanks.

**Comment by aprilthepink** [comment]
deployed a hotfix for now..
